package com.aegis.core.action.handler;

import com.aegis.core.browser.Browser;
import com.aegis.model.action.Action;
import com.aegis.model.action.ActionType;
import com.aegis.model.context.MissionContext;

import java.util.Objects;

/**
 * Executes NAVIGATE actions using the configured Browser. Not currently
 * generated by any CandidateActionGenerator — the only navigation today
 * is the one-time trip to the mission's baseUrl before the loop starts.
 * Built for completeness against ActionType; a future generator could
 * use this for "go back to a known URL" style exploration.
 */
public class NavigateActionHandler implements ActionHandler {

    private final Browser browser;

    public NavigateActionHandler(Browser browser) {
        this.browser = Objects.requireNonNull(browser, "browser must not be null");
    }

    @Override
    public ActionType supports() {
        return ActionType.NAVIGATE;
    }

    @Override
    public void execute(Action action, MissionContext context) {

        if (action == null) {
            throw new IllegalArgumentException("action must not be null");
        }

        if (action.target() == null || action.target().isBlank()) {
            throw new IllegalArgumentException("NAVIGATE action requires a target URL.");
        }

        browser.navigate(action.target());
    }
}
