package com.aegis.core.action.handler;

import com.aegis.core.browser.Browser;
import com.aegis.model.action.Action;
import com.aegis.model.action.ActionType;
import com.aegis.model.context.MissionContext;

import java.util.Objects;

/**
 * Executes SCROLL actions using the configured Browser. Not currently
 * generated by any CandidateActionGenerator — Playwright's click()/type()
 * already auto-scroll a target into view, so there's no live producer of
 * SCROLL candidates yet. Built for completeness against ActionType, and
 * so ActionExecutor doesn't throw "No handler registered" if one shows up
 * later (e.g. a future "reveal off-screen content" generator).
 */
public class ScrollActionHandler implements ActionHandler {

    private final Browser browser;

    public ScrollActionHandler(Browser browser) {
        this.browser = Objects.requireNonNull(browser, "browser must not be null");
    }

    @Override
    public ActionType supports() {
        return ActionType.SCROLL;
    }

    @Override
    public void execute(Action action, MissionContext context) {

        if (action == null) {
            throw new IllegalArgumentException("action must not be null");
        }

        if (action.target() == null || action.target().isBlank()) {
            throw new IllegalArgumentException("SCROLL action requires a target.");
        }

        browser.scrollTo(action.target());
    }
}
