package com.aegis.core.report;

import com.aegis.core.bug.RuleBasedBugExplainer;
import com.aegis.core.bug.RuleBasedRecommendationEngine;
import com.aegis.core.knowledge.KnowledgeConfig;
import com.aegis.core.mission.RuleBasedMissionPlanner;
import com.aegis.model.action.Action;
import com.aegis.model.action.ActionType;
import com.aegis.model.context.MissionContext;
import com.aegis.model.mission.Mission;
import com.aegis.model.mission.MissionStatus;
import com.aegis.model.observation.ElementInfo;
import com.aegis.model.observation.Observation;
import org.junit.jupiter.api.Test;

import java.time.Duration;
import java.time.Instant;
import java.util.List;
import java.util.Map;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

/** Knowledge Enrichment Layer integration — the World Model section (node dictionary, flows, journeys). */
class HtmlExplainabilityReportGeneratorTest {

    private final HtmlExplainabilityReportGenerator generator = new HtmlExplainabilityReportGenerator();

    @Test
    void nodeDictionaryUsesAutoGeneratedNamesWhenNoKnowledgeConfigIsSupplied() {

        MissionContext context = twoStateContext();

        String html = generator.generate(context, MissionStatus.SUCCESS);

        assertTrue(html.contains("Node Dictionary"));
        assertTrue(html.contains(">Login<") || html.contains("Login"));
        assertTrue(html.contains("name-source auto_title") || html.contains("name-source auto_url"));
    }

    @Test
    void nodeDictionaryUsesConfiguredNamesWhenAKnowledgeConfigOverridesThem() {

        MissionContext context = twoStateContext();

        KnowledgeConfig config = new KnowledgeConfig(1, List.of(
                new KnowledgeConfig.NodeConfig("*/login*", "login", "Login Screen", null, List.of(), Map.of()),
                new KnowledgeConfig.NodeConfig("*/dashboard*", "dashboard", "Dashboard Screen", null, List.of(), Map.of())
        ), List.of(), List.of(), null);

        MissionReportData data = MissionReportData.from(
                context, MissionStatus.SUCCESS, new RuleBasedBugExplainer(), new RuleBasedRecommendationEngine(),
                new RuleBasedMissionPlanner().plan(context.getMission()), List.of(), List.of(), config);

        String html = generator.generate(data);

        assertTrue(html.contains("Login Screen"));
        assertTrue(html.contains("Dashboard Screen"));
        assertTrue(html.contains("name-source configured"));
        assertTrue(html.contains(">configured<"));
    }

    @Test
    void rendersDeclaredFlowsAndJourneysWithFollowedThisRunIndicator() {

        MissionContext context = twoStateContext();

        KnowledgeConfig config = new KnowledgeConfig(1, List.of(),
                List.of(new KnowledgeConfig.FlowConfig("auth", "Authentication", List.of("login", "dashboard"), "desc", Map.of())),
                List.of(new KnowledgeConfig.JourneyDefinitionConfig("onboarding", "Onboarding", List.of("login", "dashboard"), "desc", Map.of(), null)),
                null);

        MissionReportData data = MissionReportData.from(
                context, MissionStatus.SUCCESS, new RuleBasedBugExplainer(), new RuleBasedRecommendationEngine(),
                new RuleBasedMissionPlanner().plan(context.getMission()), List.of(), List.of(), config);

        String html = generator.generate(data);

        assertTrue(html.contains("Authentication"));
        assertTrue(html.contains("Onboarding"));
        assertTrue(html.contains("followed this run"));
    }

    @Test
    void omitsFlowsAndJourneysSectionsWhenNoneAreDeclared() {

        String html = generator.generate(twoStateContext(), MissionStatus.SUCCESS);

        assertFalse(html.contains("<h3>Flows</h3>"));
        assertFalse(html.contains("<h3>Journeys</h3>"));
    }

    @Test
    void nodeTooltipIncludesTheDisplayNameNotJustTheRawSignature() {

        String html = generator.generate(twoStateContext(), MissionStatus.SUCCESS);

        // The tooltip now leads with a real name before the raw state signature.
        assertTrue(html.contains("Login (S1)") || html.contains("Login</title>") || html.matches("(?s).*Login.*<title>.*"));
    }

    @Test
    void rendersAPlainLanguageSummaryBeforeTheTechnicalSummarySection() {

        String html = generator.generate(twoStateContext(), MissionStatus.SUCCESS);

        assertTrue(html.contains("<h1"));
        assertTrue(html.contains("In Plain English"));
        assertTrue(html.contains("plain-summary-callout"));

        int plainSummaryIndex = html.indexOf("id=\"plain-summary\"");
        int technicalSummaryIndex = html.indexOf("id=\"summary\"");

        assertTrue(plainSummaryIndex >= 0);
        assertTrue(technicalSummaryIndex >= 0);
        assertTrue(plainSummaryIndex < technicalSummaryIndex);
    }

    @Test
    void rendersUxQualityFindingsWithSeverityBadges() {

        // twoStateContext()'s buttons have no text/name/id — a real,
        // structural MISSING_ACCESSIBLE_NAME finding, not a fabricated one.
        String html = generator.generate(twoStateContext(), MissionStatus.SUCCESS);

        assertTrue(html.contains("UX Quality"));
        assertTrue(html.contains("MISSING_ACCESSIBLE_NAME"));
        assertTrue(html.contains("badge severity-medium"));
    }

    @Test
    void omitsUxQualitySectionWhenNoFindings() {

        MissionContext context = new MissionContext(new Mission(UUID.randomUUID(), "Test", "Test", Map.of()));
        context.getExecutionState().setCurrentObservation(labeledObservation("https://example.com/login", "Login", "Log In"));

        String html = generator.generate(context, MissionStatus.SUCCESS);

        assertFalse(html.contains("<h3>UX Quality</h3>"));
        assertFalse(html.contains("<h3>Page Inspection</h3>"));
    }

    @Test
    void rendersPageInspectionFindingsWithSeverityBadges() {

        MissionContext context = new MissionContext(new Mission(UUID.randomUUID(), "Test", "Test", Map.of()));
        context.getExecutionState().setCurrentObservation(labeledObservation("https://example.com/login", "Login", "Log In"));

        com.aegis.core.knowledge.SignalLog signalLog = new com.aegis.core.knowledge.SignalLog(
                List.of(new com.aegis.core.knowledge.ConsoleSignal(
                        com.aegis.model.finding.FindingSeverity.HIGH, "ReferenceError: foo is not defined", "app.js:10",
                        "https://example.com/login", Instant.now())),
                List.of(), List.of());

        MissionReportData data = MissionReportData.from(
                context, MissionStatus.SUCCESS, new RuleBasedBugExplainer(), new RuleBasedRecommendationEngine(),
                new RuleBasedMissionPlanner().plan(context.getMission()), List.of(), List.of(), KnowledgeConfig.empty(), signalLog);

        String html = generator.generate(data);

        assertTrue(html.contains("Page Inspection"));
        assertTrue(html.contains("CONSOLE_ERROR"));
        assertTrue(html.contains("badge severity-high"));
    }

    private Observation labeledObservation(String url, String pageTitle, String buttonText) {
        List<ElementInfo> elements = List.of(new ElementInfo("button", null, null, buttonText, "button", null, true, true, "login-button"));
        return new Observation(url, pageTitle, elements, elements, List.of(), List.of(), List.of(), Instant.now());
    }

    private MissionContext twoStateContext() {

        MissionContext context = new MissionContext(new Mission(UUID.randomUUID(), "Test", "Test", Map.of()));

        context.getExecutionState().setCurrentObservation(observation("https://example.com/login", "Login", "login-button"));
        context.getExecutionState().addAction(click("login-button"));
        context.getExecutionState().setCurrentObservation(observation("https://example.com/dashboard", "Dashboard", "logout-link"));

        return context;
    }

    private Observation observation(String url, String pageTitle, String elementLocator) {
        List<ElementInfo> elements = List.of(new ElementInfo("button", null, null, null, "button", null, true, true, elementLocator));
        return new Observation(url, pageTitle, elements, elements, List.of(), List.of(), List.of(), Instant.now());
    }

    private Action click(String target) {
        return new Action(UUID.randomUUID(), ActionType.CLICK, target, null, "test", 0.8, "test", Duration.ofSeconds(5), Instant.now(), "button");
    }
}
